[package]
name = "irox-build-rs"
description = ""
keywords = ["irox"]
categories = []
version= "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[features]
git = ["dep:git2"]

[dependencies]
git2 = { workspace = true, optional = true}

[[example]]
name = "example"
required-features = ["git"]