[package]
name = "irox-mbtiles"
description = "Interface to work with MBTiles imagery files"
keywords = ["irox", "mbtiles", "tiles", "encoding", "decoding"]
categories = ["science::geo", "parser-implementations", "encoding"]
version= "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
irox-units.workspace = true
irox-carto.workspace = true
irox-tools.workspace = true

[dev-dependencies]
irox-tools = {workspace = true}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rusqlite.workspace = true