[package]
name = "irox-git-tools"
description = "Tools and wrappers to help with GitOps"
keywords = ["irox", "git"]
categories = ["config", "development-tools::build-utils"]
version = "0.2.2"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
irox-tools.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
git2.workspace = true