[package]
name = "irox-types"
description = "Enums and structs to describe Rust's basic type system"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true

[features]
default = []
syn = ["dep:syn"]

[dependencies]
irox-enums.workspace = true
irox-enums_derive.workspace = true
syn = {workspace = true, optional = true}
