// SPDX-License-Identifier: MIT
// Copyright 2026 IROX Contributors
//

use core::fmt::Write;

pub const EVEN_WORDS: [&str; 256] = [
    "aardvark",
    "absurd",
    "accrue",
    "acme",
    "adrift",
    "adult",
    "afflict",
    "ahead",
    "aimless",
    "Algol",
    "allow",
    "alone",
    "ammo",
    "ancient",
    "apple",
    "artist",
    "assume",
    "Athens",
    "atlas",
    "Aztec",
    "baboon",
    "backfield",
    "backward",
    "banjo",
    "beaming",
    "bedlamp",
    "beehive",
    "beeswax",
    "befriend",
    "Belfast",
    "berserk",
    "billiard",
    "bison",
    "blackjack",
    "blockade",
    "blowtorch",
    "bluebird",
    "bombast",
    "bookshelf",
    "brackish",
    "breadline",
    "breakup",
    "brickyard",
    "briefcase",
    "Burbank",
    "button",
    "buzzard",
    "cement",
    "chairlift",
    "chatter",
    "checkup",
    "chisel",
    "choking",
    "chopper",
    "Christmas",
    "clamshell",
    "classic",
    "classroom",
    "cleanup",
    "clockwork",
    "cobra",
    "commence",
    "concert",
    "cowbell",
    "crackdown",
    "cranky",
    "crowfoot",
    "crucial",
    "crumpled",
    "crusade",
    "cubic",
    "dashboard",
    "deadbolt",
    "deckhand",
    "dogsled",
    "dragnet",
    "drainage",
    "dreadful",
    "drifter",
    "dropper",
    "drumbeat",
    "drunken",
    "Dupont",
    "dwelling",
    "eating",
    "edict",
    "egghead",
    "eightball",
    "endorse",
    "endow",
    "enlist",
    "erase",
    "escape",
    "exceed",
    "eyeglass",
    "eyetooth",
    "facial",
    "fallout",
    "flagpole",
    "flatfoot",
    "flytrap",
    "fracture",
    "framework",
    "freedom",
    "frighten",
    "gazelle",
    "Geiger",
    "glitter",
    "glucose",
    "goggles",
    "goldfish",
    "gremlin",
    "guidance",
    "hamlet",
    "highchair",
    "hockey",
    "indoors",
    "indulge",
    "inverse",
    "involve",
    "island",
    "jawbone",
    "keyboard",
    "kickoff",
    "kiwi",
    "klaxon",
    "locale",
    "lockup",
    "merit",
    "minnow",
    "miser",
    "Mohawk",
    "mural",
    "music",
    "necklace",
    "Neptune",
    "newborn",
    "nightbird",
    "Oakland",
    "obtuse",
    "offload",
    "optic",
    "orca",
    "payday",
    "peachy",
    "pheasant",
    "physique",
    "playhouse",
    "Pluto",
    "preclude",
    "prefer",
    "preshrunk",
    "printer",
    "prowler",
    "pupil",
    "puppy",
    "python",
    "quadrant",
    "quiver",
    "quota",
    "ragtime",
    "ratchet",
    "rebirth",
    "reform",
    "regain",
    "reindeer",
    "rematch",
    "repay",
    "retouch",
    "revenge",
    "reward",
    "rhythm",
    "ribcage",
    "ringbolt",
    "robust",
    "rocker",
    "ruffled",
    "sailboat",
    "sawdust",
    "scallion",
    "scenic",
    "scorecard",
    "Scotland",
    "seabird",
    "select",
    "sentence",
    "shadow",
    "shamrock",
    "showgirl",
    "skullcap",
    "skydive",
    "slingshot",
    "slowdown",
    "snapline",
    "snapshot",
    "snowcap",
    "snowslide",
    "solo",
    "southward",
    "soybean",
    "spaniel",
    "spearhead",
    "spellbind",
    "spheroid",
    "spigot",
    "spindle",
    "spyglass",
    "stagehand",
    "stagnate",
    "stairway",
    "standard",
    "stapler",
    "steamship",
    "sterling",
    "stockman",
    "stopwatch",
    "stormy",
    "sugar",
    "surmount",
    "suspense",
    "sweatband",
    "swelter",
    "tactics",
    "talon",
    "tapeworm",
    "tempest",
    "tiger",
    "tissue",
    "tonic",
    "topmost",
    "tracker",
    "transit",
    "trauma",
    "treadmill",
    "Trojan",
    "trouble",
    "tumor",
    "tunnel",
    "tycoon",
    "uncut",
    "unearth",
    "unwind",
    "uproot",
    "upset",
    "upshot",
    "vapor",
    "village",
    "virus",
    "Vulcan",
    "waffle",
    "wallet",
    "watchword",
    "wayside",
    "willow",
    "woodlark",
    "Zulu",
];
pub const ODD_WORDS: [&str; 256] = [
    "adroitness",
    "adviser",
    "aftermath",
    "aggregate",
    "alkali",
    "almighty",
    "amulet",
    "amusement",
    "antenna",
    "applicant",
    "Apollo",
    "armistice",
    "article",
    "asteroid",
    "Atlantic",
    "atmosphere",
    "autopsy",
    "Babylon",
    "backwater",
    "barbecue",
    "belowground",
    "bifocals",
    "bodyguard",
    "bookseller",
    "borderline",
    "bottomless",
    "Bradbury",
    "bravado",
    "Brazilian",
    "breakaway",
    "Burlington",
    "businessman",
    "butterfat",
    "Camelot",
    "candidate",
    "cannonball",
    "Capricorn",
    "caravan",
    "caretaker",
    "celebrate",
    "cellulose",
    "certify",
    "chambermaid",
    "Cherokee",
    "Chicago",
    "clergyman",
    "coherence",
    "combustion",
    "commando",
    "company",
    "component",
    "concurrent",
    "confidence",
    "conformist",
    "congregate",
    "consensus",
    "consulting",
    "corporate",
    "corrosion",
    "councilman",
    "crossover",
    "crucifix",
    "cumbersome",
    "customer",
    "Dakota",
    "decadence",
    "December",
    "decimal",
    "designing",
    "detector",
    "detergent",
    "determine",
    "dictator",
    "dinosaur",
    "direction",
    "disable",
    "disbelief",
    "disruptive",
    "distortion",
    "document",
    "embezzle",
    "enchanting",
    "enrollment",
    "enterprise",
    "equation",
    "equipment",
    "escapade",
    "Eskimo",
    "everyday",
    "examine",
    "existence",
    "exodus",
    "fascinate",
    "filament",
    "finicky",
    "forever",
    "fortitude",
    "frequency",
    "gadgetry",
    "Galveston",
    "getaway",
    "glossary",
    "gossamer",
    "graduate",
    "gravity",
    "guitarist",
    "hamburger",
    "Hamilton",
    "handiwork",
    "hazardous",
    "headwaters",
    "hemisphere",
    "hesitate",
    "hideaway",
    "holiness",
    "hurricane",
    "hydraulic",
    "impartial",
    "impetus",
    "inception",
    "indigo",
    "inertia",
    "infancy",
    "inferno",
    "informant",
    "insincere",
    "insurgent",
    "integrate",
    "intention",
    "inventive",
    "Istanbul",
    "Jamaica",
    "Jupiter",
    "leprosy",
    "letterhead",
    "liberty",
    "maritime",
    "matchmaker",
    "maverick",
    "Medusa",
    "megaton",
    "microscope",
    "microwave",
    "midsummer",
    "millionaire",
    "miracle",
    "misnomer",
    "molasses",
    "molecule",
    "Montana",
    "monument",
    "mosquito",
    "narrative",
    "nebula",
    "newsletter",
    "Norwegian",
    "October",
    "Ohio",
    "onlooker",
    "opulent",
    "Orlando",
    "outfielder",
    "Pacific",
    "pandemic",
    "Pandora",
    "paperweight",
    "paragon",
    "paragraph",
    "paramount",
    "passenger",
    "pedigree",
    "Pegasus",
    "penetrate",
    "perceptive",
    "performance",
    "pharmacy",
    "phonetic",
    "photograph",
    "pioneer",
    "pocketful",
    "politeness",
    "positive",
    "potato",
    "processor",
    "provincial",
    "proximate",
    "puberty",
    "publisher",
    "pyramid",
    "quantity",
    "racketeer",
    "rebellion",
    "recipe",
    "recover",
    "repellent",
    "replica",
    "reproduce",
    "resistor",
    "responsive",
    "retraction",
    "retrieval",
    "retrospect",
    "revenue",
    "revival",
    "revolver",
    "sandalwood",
    "sardonic",
    "Saturday",
    "savagery",
    "scavenger",
    "sensation",
    "sociable",
    "souvenir",
    "specialist",
    "speculate",
    "stethoscope",
    "stupendous",
    "supportive",
    "surrender",
    "suspicious",
    "sympathy",
    "tambourine",
    "telephone",
    "therapist",
    "tobacco",
    "tolerance",
    "tomorrow",
    "torpedo",
    "tradition",
    "travesty",
    "trombonist",
    "truncated",
    "typewriter",
    "ultimate",
    "undaunted",
    "underfoot",
    "unicorn",
    "unify",
    "universe",
    "unravel",
    "upcoming",
    "vacancy",
    "vagabond",
    "vertigo",
    "Virginia",
    "visitor",
    "vocalist",
    "voyager",
    "warranty",
    "Waterloo",
    "whimsical",
    "Wichita",
    "Wilmington",
    "Wyoming",
    "yesteryear",
    "Yucatan",
];
///
/// Gets a single unique word from the wordlist
pub fn get_word(data: u8, is_even: bool) -> &'static str {
    let list = if is_even { EVEN_WORDS } else { ODD_WORDS };
    if let Some(s) = list.get(data as usize) {
        s
    } else {
        ""
    }
}
/// Get the set of matching words for the provided bytes.
pub fn get_words<const N: usize>(data: [u8; N]) -> [&'static str; N] {
    let mut out = [""; N];
    for (idx, (d, out)) in data.iter().zip(&mut out).enumerate() {
        let is_even = idx & 0x01 == 0x00;
        *out = get_word(*d, is_even);
    }
    out
}

/// Writes the set of associated words to the output writer
pub fn write_words<T: Write>(data: &[u8], sep: &str, out: &mut T) -> core::fmt::Result {
    let mut first = true;
    for (idx, d) in data.iter().enumerate() {
        let is_even = idx & 0x01 == 0x00;
        let word = get_word(*d, is_even);
        if !first {
            write!(out, "{sep}")?;
        }
        first = false;
        write!(out, "{word}")?;
    }
    Ok(())
}

crate::cfg_feature_alloc! {
    extern crate alloc;
    /// Creates a string based on the words for the provided data, separated with the separator
    ///
    /// ```
    /// let result = words_to_string(&[0x70, 0x01, 0x02, 0xFF], "-");
    /// assert_eq!(result, "judo-acid-also-zoom");
    /// ```
    pub fn words_to_string(data: &[u8], separator: &str) -> alloc::string::String {
        let mut out = alloc::string::String::new();
        let mut first = true;
        for d in data {
            let is_even = d & 0x01 == 0x00;
            let word = get_word(*d, is_even);
            if !first {
                out += separator;
            }
            first = false;
            out += word;
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use crate::hash::sha2wordlist::get_words;
    use crate::hex;

    #[test]
    pub fn test1() {
        assert_eq!(["aardvark"], get_words([0x0]));
        assert_eq!(["guidance", "bottomless"], get_words([0x70, 0x19]));
    }

    #[test]
    #[cfg(feature = "alloc")]
    pub fn test2() {
        let data = [0x70, 0x01, 0x02, 0xFF];
        let separator = "-";
        let expected = "guidance-adviser-accrue-Yucatan";
        let result = crate::hash::sha2wordlist::words_to_string(&data, separator);
        assert_eq!(result, expected);
    }

    #[test]
    pub fn test3() {
        let words = get_words(hex!("E58294F2E9A227486E8B061B31CC528FD7FA8919"));
        assert_eq!(
            words,
            [
                "topmost",
                "Istanbul",
                "Pluto",
                "vagabond",
                "treadmill",
                "Pacific",
                "brackish",
                "dictator",
                "goldfish",
                "Medusa",
                "afflict",
                "bravado",
                "chatter",
                "revolver",
                "Dupont",
                "midsummer",
                "stopwatch",
                "whimsical",
                "nightbird",
                "bottomless"
            ]
        );
    }
    #[test]
    pub fn test4() {
        let words = get_words(hex!(
            "bc98b3c33874689127715ae793d619fcc9d090ad8bb13c9714967a82ed5b2c8d"
        ));
        assert_eq!(
            words,
            [
                "showgirl",
                "narrative",
                "scallion",
                "replica",
                "classic",
                "hydraulic",
                "frighten",
                "miracle",
                "brackish",
                "hideaway",
                "enlist",
                "truncated",
                "playhouse",
                "speculate",
                "bedlamp",
                "Wilmington",
                "spearhead",
                "savagery",
                "peachy",
                "perceptive",
                "obtuse",
                "photograph",
                "cobra",
                "mosquito",
                "baboon",
                "monument",
                "keyboard",
                "Istanbul",
                "tunnel",
                "exodus",
                "Burbank",
                "microscope"
            ]
        );
    }
}
