[package]
name = "irox-downloader"
description = "IROX's CLI Download Manager Tool"
keywords = ["irox"]
categories = ["command-line-utilities"]
version= "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
