[package]
name = "crates-caching-proxy-libs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6", features = ["http2", "macros"] }
axum-core = { version = "0.3" }
axum-extra = { version = "0.7", features = ["typed-routing"] }
hyper = { version = "0.14" }
tokio = { version = "1.26", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.7" }
clap = { version = "4.1", features = ["derive"] }
git2 = { version = "0.16" }
bytes = { version = "1.4" }
