// SPDX-License-Identifier: MIT
// Copyright 2023 IROX Contributors
//

pub static CARGO_ENV_VARIABLES: [&str; 26] = [
    "CARGO_PKG_VERSION",
    "CARGO_PKG_VERSION_MAJOR",
    "CARGO_PKG_VERSION_MINOR",
    "CARGO_PKG_VERSION_PATCH",
    "CARGO_PKG_VERSION_PRE",
    "CARGO_PKG_AUTHORS",
    "CARGO_PKG_NAME",
    "CARGO_PKG_DESCRIPTION",
    "CARGO_PKG_HOMEPAGE",
    "CARGO_PKG_REPOSITORY",
    "CARGO_PKG_LICENSE",
    "CARGO_PKG_LICENSE_FILE",
    "CARGO_PKG_RUST_VERSION",
    "CARGO_PKG_README",
    "CARGO_PKG_CRATE_NAME",
    "CARGO_PKG_BIN_NAME",
    "CARGO_CFG_TARGET_FAMILY",
    "CARGO_CFG_TARGET_OS",
    "CARGO_CFG_TARGET_ARCH",
    "CARGO_CFG_TARGET_VENDOR",
    "CARGO_CFG_TARGET_HAS_ATOMIC",
    "CARGO_CFG_TARGET_ENV",
    "CARGO_CFG_TARGET_POINTER_WIDTH",
    "CARGO_CFG_TARGET_ENDIAN",
    "CARGO_CFG_TARGET_FEATURE",
    "CARGO_PRIMARY_PACKAGE",
];

pub static RUSTC_ENV_VARIABLES: [&str; 10] = [
    "PROCESSOR_ARCHITECTURE",
    "PROCESSOR_IDENTIFIER",
    "PROCESSOR_LEVEL",
    "PROCESSOR_REVISION",
    "TARGET",
    "HOST",
    "PROFILE",
    "RUSTUP_TOOLCHAIN",
    "OPT_LEVEL",
    "DEBUG",
];
