[package]
name = "irox-tools"
description = "Stuff that should have been in the Rust STL, but aren't"
keywords = ["irox", "tools"]
categories = ["algorithms", "data-structures", "mathematics", "encoding", "network-programming"]
version= "0.10.3"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme = "README.md"
repository.workspace = true

[lints]
workspace = true

[dependencies]
irox-bits.workspace = true
serde = {workspace = true, optional = true}

[dev-dependencies]
irox-bits = {workspace = true, features = ["alloc"]}
criterion.workspace = true
core_affinity.workspace = true
serde_json.workspace = true

[features]
default = []
std = ["irox-bits/std", "alloc"]
alloc = ["irox-bits/alloc"]
serde = ["dep:serde"]

_toobig-tests = [] # slow tests that take way too long to run normally.

[lib]
bench = false

[[bench]]
name = "random"
harness = false
[[bench]]
name = "atomics"
harness = false
[[bench]]
name = "hashes"
harness = false

[[test]]
name = "shatests"
required-features = ["std"]

[[test]]
name = "hmactests"
required-features = ["std"]

[[test]]
name = "blake2tests"
required-features = ["std"]

[[example]]
name = "ansi"
required-features = ["std"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
